### PR TITLE
ING-599: Return index exists error for search index UUID mismatch

### PR DESCRIPTION
**Pull request by chvck**

### CODE REVIEW

**Comment by chvck** [comment]
I could be convinced that this should be a different error, but it seems to me that it is fundamentally an already exists error.

**Comment by dnault** [comment]
I believe CNG should return the same class of error it does for a CAS mismatch, since the UUID is effectively the index's CAS value.

**Comment by chvck** [comment]
> I believe CNG should return the same class of error it does for a CAS mismatch, since the UUID is effectively the index's CAS value.

That was my thinking too. This is gocbcorex rather than CNG though :)

**Comment by dnault** [comment]
:disappear:

**Pull request merged**
